export const MOTIVATIONAL_QUOTES = [
  "Every morning is a blank canvas. Paint it beautifully.",
  "Rise up, start fresh, see the bright opportunity in each day.",
  "Win the morning, win the day.",
  "Your future is created by what you do today, not tomorrow.",
  "The secret of your future is hidden in your daily routine.",
  "Make today a masterpiece.",
  "Morning is the start of every everyday miracle.",
  "Don't wait for the perfect moment. Take the moment and make it perfect.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Embrace the glorious mess that you are and start taking action.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Today is a new day. You will get out of it just what you put into it.",
  "Do something today that your future self will thank you for.",
  "Little by little, a little becomes a lot.",
  "Let your soul shine as bright as the morning sun.",
  "Great things never come from comfort zones.",
  "Focus on your goal. Don't look in any direction but ahead.",
  "Breathe in confidence, exhale doubt.",
  "The only bad workout is the one that didn't happen.",
  "Consistency is what transforms average into excellence.",
  "Your mind is a powerful thing. Fill it with positive thoughts.",
  "The best preparation for tomorrow is doing your best today.",
  "Discipline is choosing between what you want now and what you want most.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Small daily improvements over time lead to stunning results.",
  "Every morning is a chance at a new day.",
  "Start where you are. Use what you have. Do what you can.",
  "Don't downgrade your dream just to fit your reality.",
  "Be stronger than your excuses.",
  "A river cuts through rock not because of its power but its persistence."
];
